/* This implements an alternative logger to the one found in the standard
 * library with support for more logging levels, formatters and handlers.
 * The main goal is to provide easy and flexible way to handle new handlers and formats
 * Author: Robert Zaremba
 *
 * https://github.com/scale-it/go-log
 */
package log

import (
	"errors"
	"fmt"
	"io"
	"os"
	"sync"
)

// Flags from std log package
// These flags define which text to prefix to each log entry generated by the Logger.
const (
	// Bits or'ed together to control what's printed. There is no control over the
	// order they appear (the order listed here) or the format they present (as
	// described in the comments).  A colon appears after these items:
	//	2009/01/23 01:23:23.123123 /a/b/c/d.go:23: message
	Ldate         = 1 << iota     // the date: 2009/01/23
	Ltime                         // the time: 01:23:23
	Lmicroseconds                 // microsecond resolution: 01:23:23.123123.  assumes Ltime.
	Llongfile                     // full file name and line number: /a/b/c/d.go:23
	Lshortfile                    // final file name element and line number: d.go:23. overrides Llongfile
	LstdFlags     = Ldate | Ltime // initial values for the standard logger
)

// Represents how critical the logged
// message is.
type Level uint8

var Levels = struct {
	Trace    Level
	Debug    Level
	Info     Level
	Warning  Level
	Error    Level
	Critical Level
}{0, 10, 20, 30, 40, 50}

// Verbose names of the levels
var levelStrings = map[Level]string{
	Levels.Trace:    "TRACE",
	Levels.Debug:    "DEBUG",
	Levels.Info:     "INFO ",
	Levels.Warning:  "WARN ",
	Levels.Error:    "ERROR",
	Levels.Critical: "CRITIC",
}

// Verbose and colored names of the levels
var levelCStrings = map[Level]string{
	Levels.Trace:    levelStrings[Levels.Trace],
	Levels.Debug:    levelStrings[Levels.Debug],
	Levels.Info:     AnsiEscape(MAGENTA, levelStrings[Levels.Info], OFF),
	Levels.Warning:  AnsiEscape(YELLOW, levelStrings[Levels.Warning], OFF),
	Levels.Error:    AnsiEscape(RED, levelStrings[Levels.Error], OFF),
	Levels.Critical: AnsiEscape(RED, BOLD, levelStrings[Levels.Critical], OFF),
}

// Returns an log Level which name match given string.
// If there is no such Level, then Levels.Debug is returned
func String2Level(level string) (Level, error) {
	if level == "" {
		return Levels.Debug, errors.New("level is empty")
	}
	for li, ls := range levelStrings {
		if ls == level {
			return li, nil
		}
	}
	return Levels.Debug, errors.New("Wrong log level " + level)
}

type handler struct {
	writer io.Writer
	level  Level
	fmt    Formatter
}

type Logger struct {
	mtx      sync.Mutex
	handlers []handler
}

var vv map[io.Writer]sync.Mutex

// Instantiate a new Logger
func New() *Logger {
	return &Logger{sync.Mutex{}, make([]handler, 0)}
}

// Convenience function to create logger with StdFormatter
func NewStd(w io.Writer, level Level, flag int, colored bool) *Logger {
	l := Logger{sync.Mutex{}, make([]handler, 0)}
	l.AddHandler(w, level, StdFormatter{"", flag, colored})
	return &l
}

/* LOGGER
 * ------
 */

// Adds a handler, specifying the maximum log Level
// you want to be written to this output. For instance,
// if you pass Warning for level, all logs of type
// Warning, Error, and Critical would be logged to this handler.
func (this *Logger) AddHandler(writer io.Writer, level Level, fm Formatter) {
	this.mtx.Lock()
	this.handlers = append(this.handlers, handler{writer, level, fm})
	this.mtx.Unlock()
}

// Logs a message for the given level. Most callers will likely
// prefer to use one of the provided convenience functions (Debug, Info...).
func (this *Logger) Log(level Level, msg string) {
	var out []byte
	for _, h := range this.handlers {
		if h.level <= level {
			out = h.fmt.Format(level, msg)
			this.mtx.Lock()
			h.writer.Write(out)
			this.mtx.Unlock()
		}
	}
}

// Logs a formatted message message for the given level.
// Wrapper around Log method
func (this *Logger) Logf(level Level, format string, v ...interface{}) {
	this.Log(level, fmt.Sprintf(format+"\n", v...))
}

// Convenience function
func (this *Logger) Trace(v ...interface{}) {
	// TODO: split the string
	this.Log(Levels.Trace, fmt.Sprintln(v...))
}

// Convenience function
func (this *Logger) Tracef(format string, v ...interface{}) {
	// TODO: split the string
	this.Log(Levels.Trace, fmt.Sprintf(format+"\n", v...))
}

// Convenience function
func (this *Logger) Debug(v ...interface{}) {
	this.Log(Levels.Debug, fmt.Sprintln(v...))
}

// Convenience function
func (this *Logger) Debugf(format string, v ...interface{}) {
	this.Log(Levels.Debug, fmt.Sprintf(format+"\n", v...))
}

// Convenience function
func (this *Logger) Info(v ...interface{}) {
	this.Log(Levels.Info, fmt.Sprintln(v...))
}

// Convenience function
func (this *Logger) Infof(format string, v ...interface{}) {
	this.Log(Levels.Info, fmt.Sprintf(format+"\n", v...))
}

// Convenience function
func (this *Logger) Warning(v ...interface{}) {
	this.Log(Levels.Warning, fmt.Sprintln(v...))
}

// Convenience function
func (this *Logger) Warningf(format string, v ...interface{}) {
	this.Log(Levels.Warning, fmt.Sprintf(format+"\n", v...))
}

// Convenience function
func (this *Logger) Error(v ...interface{}) {
	this.Log(Levels.Error, fmt.Sprintln(v...))
}

// Convenience function
func (this *Logger) Errorf(format string, v ...interface{}) {
	this.Log(Levels.Error, fmt.Sprintf(format+"\n", v...))
}

// Convenience function, will not terminate the program
func (this *Logger) Critical(v ...interface{}) {
	this.Log(Levels.Critical, fmt.Sprintln(v...))
}

// Convenience function, will not terminate the program
func (this *Logger) Criticalf(format string, v ...interface{}) {
	this.Log(Levels.Critical, fmt.Sprintf(format+"\n", v...))
}

// Convenience function, will terminate the program
func (this *Logger) Fatal(v ...interface{}) {
	this.Log(Levels.Critical, fmt.Sprintln(v...))
	os.Exit(1)
}

// Convenience function, will terminate the program
func (this *Logger) Fatalf(format string, v ...interface{}) {
	this.Log(Levels.Critical, fmt.Sprintf(format+"\n", v...))
	os.Exit(1)
}

// Convinience function to support io.Writer interface
func (this *Logger) Write(p []byte) (n int, err error) {
	n = len(p)
	this.Log(0, string(p))
	return
}
